ingress_svc:
  name: traefik-ingress-service
  namespace: kube-system

image:
  repository: pennlabs/ingress-bouncer
  pullPolicy: Always
  tag: latest

cronjob:
  schedule: "*/5 * * * *"
  successLimit: 1
  failureLimit: 1
