---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ingress-bouncer
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failureLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: ingress-bouncer
          containers:
            - name: bouncer
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: INGRESS_SVC_NAME
                  value: "{{ .Values.ingress_svc.name }}"
                - name: INGRESS_SVC_NS
                  value: "{{ .Values.ingress_svc.namespace }}"
